name: animated_mouse_cursor
description: "Flutter package for using custom mouse cursor on flutter web"
version: 0.0.2
homepage: "https://github.com/bijith-git/animated_mouse_cursor"
repository: "https://github.com/bijith-git/animated_mouse_cursor"
issue_tracker: "https://github.com/bijith-git/animated_mouse_cursor/issues"

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
